apiVersion: apps/v1
kind: Deployment
metadata:
  name: "scalr-agent-controller"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
    app.kubernetes.io/name: scalr-agent
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      {{- include "agent-job.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with (merge (deepCopy .Values.global.podAnnotations) .Values.controller.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.agent.tokenExistingSecret.name }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "agent-job.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agent-job.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      {{- with (default .Values.agent.podSecurityContext .Values.controller.podSecurityContext) }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          {{- $image := .Values.controller.image }}
          {{- if not $image.repository }}
            {{- $image = .Values.agent.image }}
          {{- end }}
          {{- $registry := .Values.global.imageRegistry }}
          {{- if $registry }}
          image: "{{ $registry }}/{{ $image.repository }}:{{ $image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ $image.repository }}:{{ $image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ $image.pullPolicy | default .Values.agent.image.pullPolicy }}
          command: ["python", "-m", "tacoagent.cmd"]
          {{- with (default .Values.agent.securityContext .Values.controller.securityContext) }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SCALR_URL
              value: {{ .Values.agent.url | quote }}
            - name: SCALR_AGENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.agent.tokenExistingSecret.name | default (include "agent-job.name" .) }}
                  key: {{ .Values.agent.tokenExistingSecret.key | default "token" }}
                  optional: false
            - name: SCALR_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SCALR_AGENT_DATA_DIR
              value: "{{ .Values.agent.dataDir }}"
            - name: SCALR_AGENT_DRIVER
              value: "kubernetes-job"
            {{- range $key, $value := .Values.agent.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.controller.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          volumeMounts:
            - name: data-dir
              mountPath: "{{ .Values.agent.dataDir }}"
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: data-dir
        emptyDir: {}
      terminationGracePeriodSeconds: {{ .Values.controller.terminationGracePeriodSeconds }}
