{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.persistentVolumeClaim.claimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agent-job.fullname" . }}-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
  {{- with (include "agent-job.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.persistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.persistentVolumeClaim.storage }}
  {{- with .Values.persistence.data.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ ternary "" . (eq . "-") | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.persistence.cache.enabled (not .Values.persistence.cache.persistentVolumeClaim.claimName) (not .Values.persistence.cache.hostPath.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agent-job.fullname" . }}-cache
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-job.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
  {{- with (include "agent-job.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.cache.persistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.persistentVolumeClaim.storage }}
  {{- with .Values.persistence.cache.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ ternary "" . (eq . "-") | quote }}
  {{- end }}
{{- end }}
