apiVersion: v2
name: agent-job
description: |
  A Helm chart for deploying the Scalr Agent on a Kubernetes cluster.
  It uses a job-based model, where each Scalr Run is isolated
  in its own Kubernetes Job.
type: application
version: 0.6.3
appVersion: 1.2.1
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-job
icon: https://raw.githubusercontent.com/Scalr/agent-helm/master/charts/agent-job/assets/icon.png
maintainers:
  - name: scalr
    email: packages@scalr.com
sources:
  - https://github.com/Scalr/agent-helm/tree/master/charts/agent-job
keywords:
  - scalr
  - agent
  - terraform
  - opentofu
  - iac
  - job
  - multi-tenancy
annotations:
  artifacthub.io/displayName: Scalr Agent (Job)
  artifacthub.io/category: integration-delivery
  artifacthub.io/signKey: |
    fingerprint: 90CF6AB88FFAFFD2BE1A40291C0DB0953B416AA6
    url: https://scalr.github.io/agent-helm/public-key.asc
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.scalr.io/docs/self-hosted-agents-pools
    - name: Scalr
      url: https://scalr.com
    - name: Source
      url: https://github.com/Scalr/agent-helm/tree/master/charts/agent-job
    - name: Changelog
      url: https://github.com/Scalr/agent-helm/blob/master/charts/agent-job/CHANGELOG.md
  artifacthub.io/crds: |
    - kind: AgentTaskTemplate
      version: v1alpha1
      name: agenttasktemplate
      displayName: Agent Task Template
      description: |
        Defines a template for tasks that the Scalr Agent controller materializes
        into Kubernetes Jobs for each Scalr Run.
