# Default values for agent-k8s.

agent:
  # -- The Scalr url.
  url: ""
  # -- The agent pool token.
  token: ""
  # -- The name of the secret containing the agent pool token. Secret is created if left empty.
  tokenExistingSecret: ""
  # -- The key of the secret containing the agent pool token.
  tokenExistingSecretKey: "token"
  # -- The directory where the Scalr Agent stores run data, configuration versions, and the OpenTofu/Terraform provider cache.
  # This directory must be readable, writable, and executable to support the execution of OpenTofu/Terraform provider binaries.
  # It is mounted to the volume defined in the persistence section.
  dataDir: "/var/lib/scalr-agent"

# -- Image pull secrets for private registries.
imagePullSecrets: []
# -- Override the chart name portion of resource names.
nameOverride: ""
# -- Override the full name of resources (takes precedence over nameOverride).
fullnameOverride: ""

# -- Kubernetes Node Selector for assigning controller agent to specific node in the cluster.
# Example: `--set controllerNodeSelector."cloud\\.google\\.com\\/gke-nodepool"="scalr-agent-controller-pool"`
controllerNodeSelector: {}
# -- Kubernetes Node Selector for assigning worker agents and scheduling agent tasks to specific nodes in the cluster.
# The selector must match a node's labels for the pod to be scheduled on that node.
# Expects input structure as per specification <https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core>.
# Example: `--set controllerTolerations[0].operator=Equal,controllerTolerations[0].effect=NoSchedule,controllerTolerations[0].key=dedicated,controllerTolerations[0].value=scalr-agent-controller-pool`
controllerTolerations: []
# -- Kubernetes Node Selector for the agent worker and the agent task pods.
# Example: `--set workerNodeSelector."cloud\\.google\\.com\\/gke-nodepool"="scalr-agent-worker-pool"`
workerNodeSelector: {}
# -- Kubernetes Node Tolerations for the agent worker and the agent task pods.
# Expects input structure as per specification <https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core>.
# Example: `--set workerTolerations[0].operator=Equal,workerTolerations[0].effect=NoSchedule,workerTolerations[0].key=dedicated,workerTolerations[0].value=scalr-agent-worker-pool`
workerTolerations: []

serviceAccount:
  # -- Create a Kubernetes service account for the Scalr Agent.
  create: true
  # -- Whether to automount the service account token in the Scalr Agent pod.
  automountToken: true
  # -- Annotations for the service account.
  annotations: {}
  # -- Additional labels for the service account.
  labels: {}
  # -- Name of the service account. Generated if not set and 'create' is true.
  name: ""
  # -- The token expiration period.
  tokenTTL: 3600

# -- Amazon EFS file system ID to use EFS storage as data home directory.
efsVolumeHandle: ""

# -- Amazon EFS mount options to define how the EFS storage volume should be mounted.
efsMountOptions:
  - acregmin=1
  - acregmax=3
  - acdirmin=1
  - acdirmax=3

# -- Security context for Scalr Agent pod.
podSecurityContext:
  runAsNonRoot: false
  fsGroup: 0

# -- Security context for Scalr Agent container.
securityContext:
  # -- Run container in privileged mode. Enable only if required.
  privileged: false
  # -- Proc mount type. Valid values: Default, Unmasked, Host.
  procMount: Default
  # -- Restrict container capabilities for security.
  capabilities:
    drop:
      - ALL
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

# -- The Agent Pods annotations.
podAnnotations: {}

# -- Controller specific pod annotations (merged with podAnnotations, overrides duplicate keys)
controllerPodAnnotations: {}

# -- Worker specific pod annotations (merged with podAnnotations, overrides duplicate keys)
workerPodAnnotations: {}

# -- Apply NetworkPolicy to an agent pod that denies access to VM metadata service address (169.254.169.254)
restrictMetadataService: false

# -- Provides the amount of grace time prior to the agent-k8s container being forcibly terminated when marked for deletion or restarted.
terminationGracePeriodSeconds: 360

# Additional environment variables for agent containers.
# For instance to add a HTTP proxy.
extraEnv: {}
#   HTTPS_PROXY: "http://myproxy.com:3128"
#   HTTP_PROXY: "http://myproxy.com:3128"
#   NO_PROXY: "localhost,127.0.0.1"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 1024Mi

# -- Persistent storage configuration for the Scalr Agent data directory.
persistence:
  # -- Enable persistent storage. If false, uses emptyDir (ephemeral storage).
  enabled: false
  # -- Configuration for emptyDir volume (used when persistence.enabled is false).
  emptyDir:
    # -- Size limit for the emptyDir volume.
    sizeLimit: 20Gi
  # -- Configuration for persistentVolumeClaim (used when persistence.enabled is true).
  persistentVolumeClaim:
    # -- Name of an existing PVC. If empty, a new PVC is created dynamically.
    claimName: ""
    # -- Storage class for the PVC. Leave empty to use the cluster's default storage class.
    # Set to "-" to disable dynamic provisioning and require a pre-existing PVC.
    storageClassName: ""
    # -- Storage size for the PVC.
    storage: 20Gi
    # -- Access mode for the PVC. The NFS disk is expected here, so ReadWriteMany is a default.
    accessMode: ReadWriteMany
    # -- Optional subPath for mounting a specific subdirectory of the volume.
    subPath: ""


controller:
  image:
    # -- Docker repository for the Scalr Agent image.
    repository: scalr/agent
    # -- Overrides the image tag whose default is the chart appVersion.
    tag: ""
    # -- The pullPolicy for a container and the tag of the image.
    pullPolicy: IfNotPresent

worker:
  image:
      # -- Docker repository for the Scalr Agent image.
      repository: scalr/agent
      # -- Overrides the image tag whose default is the chart appVersion.
      tag: ""
      # -- The pullPolicy for a container and the tag of the image.
      pullPolicy: IfNotPresent

  runner:
    image:
      # -- Docker repository for the Scalr Agent runner image.
      repository: scalr/agent-runner
      # -- Overrides the image tag whose default is the chart appVersion.
      tag: ""
      # -- The pullPolicy for a container and the tag of the image.
      pullPolicy: IfNotPresent
