apiVersion: v2
name: agent-docker
description: |
  A Helm chart for the scalr-agent deployment on ths Kubernetes cluster,
  where runs are executed in [dind](https://hub.docker.com/_/docker) sidecar container.
  Run phases are isolated into docker containers.
type: application
version: 0.5.13
appVersion: 0.19.0
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-docker
maintainers:
  - name: scalr
    email: packages@scalr.com
