apiVersion: v2
name: agent-docker
description: |
  A Helm chart for the scalr-agent deployment on ths Kubernetes cluster,
  where runs are executed in [dind](https://hub.docker.com/_/docker) sidecar container.
  Run phases are isolated into docker containers.

  Kuberentes deployment doesn't scale on multiple replicas.
  Consequently, the capacity of compute resources that can be managed
  by a single agent remains constrained by a single node.

  Multiple Deployments can be created within a single Kubernetes cluster.

  ![Agent in Docker deployment diagram](/charts/agent-docker/assets/agent-docker-deploy-diagram.jpg)
type: application
version: 0.3.1
appVersion: "0.1.33"
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-docker
maintainers:
  - name: scalr
    email: packages@scalr.com
