# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: build-js-actions
        name: Build JS GitHub Actions
        entry: bash -c 'find ".github/actions" -mindepth 2 -maxdepth 2 -type f -name "package.json" -exec dirname {} \; | xargs -I {} npm --prefix {} run all'
        language: system
        pass_filenames: false
        files: ^\.github/actions/
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.28
    hooks:
      - id: helmlint
        files: ^\.charts/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: &compiled_js '.*\/index\.dist\.js$'
      - id: end-of-file-fixer
        exclude: *compiled_js
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: "^(charts/agent-k8s/templates|charts/agent-docker/templates|charts/agent-local/templates|charts/agent-job/templates)"
      - id: check-added-large-files
