repos:
  - repo: local
    hooks:
      - id: build-js-actions
        name: build-js-actions
        entry: bash -c 'actions_dir=".github/actions"; find "$actions_dir" -maxdepth 2 -type f -name "package.json" -exec dirname {} \; | uniq | xargs -I {} npm --prefix {} run build'
        language: system
        pass_filenames: false
