apiVersion: v2
name: agent-k8s
description: |
  A Helm chart for deploying the Scalr Agent on a Kubernetes cluster.
  Deploys an agent controller with a set of agent workers and executes runs in isolated pods.
type: application
version: 0.5.80
appVersion: 1.0.5
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-k8s
icon: https://raw.githubusercontent.com/Scalr/agent-helm/master/charts/agent-job/assets/icon.ico
maintainers:
  - name: scalr
    email: packages@scalr.com
sources:
  - https://github.com/Scalr/agent-helm/tree/master/charts/agent-k8s
keywords:
  - scalr
  - agent
  - terraform
  - opentofu
  - iac
  - multi-tenancy
annotations:
  artifacthub.io/displayName: Scalr Agent (Kubernetes)
  artifacthub.io/category: integration-delivery
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.scalr.io/docs/self-hosted-agents-pools
    - name: Scalr
      url: https://scalr.com
    - name: Source
      url: https://github.com/Scalr/agent-helm/tree/master/charts/agent-k8s
    - name: Changelog
      url: https://github.com/Scalr/agent-helm/blob/master/charts/agent-k8s/CHANGELOG.md
  artifacthub.io/images: |
    - name: agent
      image: scalr/agent:1.0.5
    - name: runner
      image: scalr/runner:0.2.0
