apiVersion: v2
name: agent-k8s
description: |
  A Helm chart for deploying the Scalr Agent on a Kubernetes cluster.
  Deploys an agent controller with a set of agent workers and executes runs in isolated pods.
type: application
version: 0.6.1
appVersion: 1.1.0
home: https://github.com/Scalr/agent-helm/tree/master/charts/agent-k8s
icon: https://raw.githubusercontent.com/Scalr/agent-helm/master/charts/agent-job/assets/icon.png
maintainers:
  - name: scalr
    email: packages@scalr.com
sources:
  - https://github.com/Scalr/agent-helm/tree/master/charts/agent-k8s
keywords:
  - scalr
  - agent
  - terraform
  - opentofu
  - iac
  - multi-tenancy
annotations:
  artifacthub.io/displayName: Scalr Agent (Kubernetes)
  artifacthub.io/category: integration-delivery
  artifacthub.io/signKey: |
    fingerprint: 90CF6AB88FFAFFD2BE1A40291C0DB0953B416AA6
    url: https://scalr.github.io/agent-helm/public-key.asc
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.scalr.io/docs/self-hosted-agents-pools
    - name: Scalr
      url: https://scalr.com
    - name: Source
      url: https://github.com/Scalr/agent-helm/tree/master/charts/agent-k8s
    - name: Changelog
      url: https://github.com/Scalr/agent-helm/blob/master/charts/agent-k8s/CHANGELOG.md
