{{ if not .Values.agent.tokenExistingSecret }}
apiVersion: v1
data:
  token: {{ required ".Values.agent.token must be provided or a pre-existing secret must be specified in .Values.agent.tokenExistingSecret!" .Values.agent.token | b64enc }}
kind: Secret
metadata:
  name: {{ include "agent-docker.name" . }}
  labels:
    {{- include "agent-docker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{ end }}