apiVersion: v1
data:
  token: {{ required ".Values.agent.token must be provided!" .Values.agent.token | b64enc }}
kind: Secret
metadata:
  name: {{ include "scalr-agent.name" . }}
  labels:
    {{- include "scalr-agent.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
