name: Update appVersion
description: |-
  This action update appVersion in all charts. It gets the appVersion from the input
  and sets it in each Chart.yaml and changes the version of Chart.yaml itself. Charts
  versions is updated using the sem-version patch stategy. All changes are made in $GITHUB_WORKSPACE.

inputs:
  app_version:
    description: The new appVersion value
    required: true

outputs:
  app_version:
    description: The update appVersion value

  chart_version:
    description: The updated Chart.yaml version value

runs:
  using: node16
  main: "index.dist.js"
