apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-local.fullname" . }}
  labels:
    {{- include "agent-local.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 100%
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "agent-local.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agent-local.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agent-local.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          env:
          {{- if .Values.extraEnv }}
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          - name: SCALR_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SCALR_URL
            value: {{ required ".Values.agent.url must be provided!" .Values.agent.url }}
          - name: SCALR_DRIVER
            value: local
          - name: SCALR_AGENT_CONCURRENCY
            value: 1
          - name: SCALR_DATA_HOME
            value: /var/lib/scalr-agent
          - name: SCALR_TOKEN
            valueFrom:
              secretKeyRef:
              {{- if .Values.agent.tokenExistingSecret }}
                {{- with .Values.agent.tokenExistingSecret }}
                  {{- toYaml . | nindent 16  }}
                {{- end }}
              {{- else }}
                name: {{ include "agent-local.name" . }}
                key: token
              {{- end }}
                optional: false
          livenessProbe:
            exec:
              command:
              - cat
              - /var/lib/agent-local/.agent.state
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 1
            timeoutSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: dockersocket
        emptyDir: {}
      - name: data
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
