{{- if not .Values.agent.tokenExistingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent-local.fullname" . }}-token
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-local.labels" . | nindent 4 }}
    {{- with .Values.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ required ".Values.agent.token must be provided or a pre-existing secret must be specified in .Values.agent.tokenExistingSecret!" .Values.agent.token | b64enc | quote }}
{{- end }}
