apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: atasks.scalr.io
spec:
  group: scalr.io
  scope: Namespaced
  names:
    kind: AgentTask
    plural: atasks
    singular: atask
    shortNames: [at]
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              jobTemplate:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            required: ["jobTemplate"]
    subresources:
      status: {}
