{{- if .Values.efsVolumeHandle -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-k8s-efs-claim
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: agent-k8s-efs-sc
  resources:
    requests:
      storage: 5Gi
{{- end }}

{{- if and .Values.persistence.enabled (not .Values.persistence.persistentVolumeClaim.claimName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "agent-k8s.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-k8s.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.persistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.persistentVolumeClaim.storage }}
  {{- if .Values.persistence.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.persistence.persistentVolumeClaim.storageClassName }}
  {{- else if eq .Values.persistence.persistentVolumeClaim.storageClassName "-" }}
  storageClassName: ""
  {{- end }}
{{- end }}
