{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-k8s-role
  namespace: {{ .Release.Namespace | quote }}
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/status"
      - "pods/log"
      - "pods/exec"
      - "configmaps"
      - "secrets"
    verbs:
      - "create"
      - "delete"
      - "get"
      - "list"
      - "patch"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-k8s-role-binding
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: agent-k8s-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
