apiVersion: v1
data:
  token: {{ required ".Values.agent.token must be provided!" .Values.agent.token | b64enc }}
kind: Secret
metadata:
  name: {{ include "agent-k8s.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-k8s.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
