{{- if .Values.efsVolumeHandle -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: agent-k8s-efs-sc
  namespace: {{ .Release.Namespace | quote }}
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
parameters:
  provisioningMode: efs-ap
  directoryPerms: "775"
mountOptions:
{{- with .Values.efsMountOptions }}
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
