name: Release Chart

on:
  push:
    branches:
      - master
    paths:
      - "chart/Chart.yaml"

permissions: {}
jobs:
  release:
    permissions:
      contents: write #  to push chart release and create a release (helm/chart-releaser-action)

    if: github.repository == 'Scalr/agent-helm'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get chart version
        id: chart_version
        run: |
          set -euo pipefail
          chart_version="$(grep -Po "(?<=^version: ).+" charts/Chart.yaml)"
          echo "::set-output name=version::${chart_version}"

      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: charts/CHANGELOG.md
          version: "v${{ steps.chart_version.outputs.version }}"

      - name: Create release notes
        run: |
          set -euo pipefail
          cat <<"EOF" > charts/RELEASE.md
          ${{ steps.changelog_reader.outputs.changes }}
          EOF

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set-up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "scalr-agent-helm-chart-{{ .Version }}"
          CR_RELEASE_NOTES_FILE: RELEASE.md
          CR_MAKE_RELEASE_LATEST: false