name: Sync appVersion
# TODO: add description of this action

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: Scalr Agent version in format x.y.z (without `agent/` prefix).
        required: true
        type: string
      upstream:
        description: |
          This input is used to link the dispatch with the upstream. It will be
          as prefix in PR name.
        required: true
        type: string


env:
  PR_BRANCH: 'actions/sync-app-version-${{ inputs.app_version }}'

jobs:
  sync-app-version:
    name: Sync appVersion
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # DEV
      - name: Printenv
        shell: bash
        run: printenv

      - name: Main
        uses: ./.github/actions/sync-app-version
        with:
            app_version: ${{inputs.app_version}}
            upstream: ${{inputs.upstream}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
