name: Test push master

on:
  push:
    branches:
      - SCALRCORE-29806

jobs:
  test-push-master:
    name: Update appVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sudo GitHub Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{vars.SUDO_GHA_APP_ID}}
          installation_id: ${{vars.SUDO_GHA_APP_INSTALLATION_ID}}
          private_key: ${{secrets.SUDO_GHA_APP_PRIVATE_KEY}}
      - name: Main
        run: |
          git fetch origin master
          git checkout master
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config credential.username oauth2 
          git config credential.helper '!f() { test "$1" = get && echo "password=${{ steps.generate_token.outputs.token }}"; }; f'
          touch test-push-master
          git add test-push-master
          git commit -m "test-push-master"
          ls -l .git/hooks/
          #git push -u origin master --force
        