name: Test push master

on:
  push:
    branches:
      - SCALRCORE-29806

jobs:
  test-push-master:
    name: Update appVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Main
        run: |
          git fetch origin master
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          touch test-push-master
          git add test-push-master
          git commit -m "test-push-master"
          git push -u origin master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}