name: Update appVersion

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: Scalr Agent version in format x.y.z (without `agent/` prefix).
        required: true
        type: string

env:
  PR_BRANCH: 'actions/update-app-version-${{ inputs.app_version }}'
  
jobs:
  update-app-version:
    name: Update appVersion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Setup helm-docs
      #   uses: ./.github/actions/setup-helm-docs
      - name: Main
        uses: ./.github/actions/update-app-version
        with:
            app_version: ${{inputs.app_version}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
