name: Update appVersion

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: Scalr Agent version in format x.y.z (without `agent/` prefix).
        required: true
        type: string

jobs:
  update-app-version:
    name: Update appVersion
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Sudo GitHub Token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{vars.SUDO_GHA_APP_ID}}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{vars.SUDO_GHA_APP_INSTALLATION_ID}}
          private_key: ${{secrets.SUDO_GHA_APP_PRIVATE_KEY}}

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup helm-docs
        uses: ./.github/actions/setup-helm-docs

      - name: Main
        uses: ./.github/actions/update-app-version
        with:
          app_version: ${{inputs.app_version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for pushed commit to be visible
        shell: bash
        run: sleep 60

      - name: Release Charts
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26 # v1.3.2
        with:
          workflow: release-charts.yaml
          ref: ${{ github.ref_name }}

  notify:
    name: Notify About Agent Helm Release
    needs: [update-app-version]
    if: failure()
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Release Failed
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "The Agent Helm Update App Version has been Failed",
              "attachments": [
                {
                  "color": "b52c2a",
                  "fields": [
                    {
                      "title": "Job URL",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
